[package]
name = "generic-btree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thunderdome = "0.6.0"

[[bench]]
name = "ord"
harness = false

[dev-dependencies]
criterion = "0.4.0"
rand = "0.8.5"
