[package]
name = "generic-btree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec = "1.10.0"
thunderdome = "0.6.0"


[dev-dependencies]
arbitrary = { version = "1.2.3", features = ["derive"] }
criterion = "0.4.0"
jumprope = "1.0.0"
rand = "0.8.5"


[[bench]]
name = "ord"
harness = false

[[bench]]
name = "rope"
harness = false

[profile.release]
debug = true
